---
__ansible_service_broker_registry_type: dockerhub
__ansible_service_broker_registry_name: dh
__ansible_service_broker_registry_url: null
__ansible_service_broker_registry_user: null
__ansible_service_broker_registry_password: null
__ansible_service_broker_registry_organization: ansibleplaybookbundle
__ansible_service_broker_registry_tag: latest
__ansible_service_broker_registry_whitelist: []
__ansible_service_broker_registry_blacklist:
  - '.*automation-broker-apb$'
__ansible_service_broker_registry_images: []
__ansible_service_broker_registry_skip_verify_tls: false
